import Head from "next/head";
import Image from "next/image";

// Components
import Banner from "../components/banner";

// Styling
import styles from "../styles/Home.module.css";
import homeStyle from "../styles/Home.module.css";

export default function Home() {
  const handleOnBannerBtnClick = () => {
    console.log("Hi Banner Button");
  };

  return (
    <div className={homeStyle.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={homeStyle.main}>
        <Banner
          buttonText="View stores nearby"
          handleOnClick={handleOnBannerBtnClick}
        />
        <div className={styles.gummyCoffee}>
          <Image
            alt="gummy-coffee-svg"
            src="/static/gummy-coffee.svg"
            width={375}
            height={400}
          />
        </div>
      </main>
    </div>
  );
}
